### ISSUE TITLE
Undefined variable $name but $this->name work

### ISSUE THREAD

**Issue by yoh** [qiqphp/qiq#12]
Hi ! Nice and interesting lib :)
I try to use Qiq but I think there is a little problem : `{{= $this->name}}` work but not `{{= $name}}` in template (Undefined variable $name).

You can easily reproduce this behavior modifying the `tests/templates/index.php` with `{{= hello($name)}}`.
It work when I use the `render()` method because I pass `string $__NAME__, array $__VARS__ = []` parameters by hand ( `$actual = ($this->template)->render('index', ['name' => 'Index']);`) but not with the `__invoke` because `$__VARS__` parameter is not pass in `render()`.

I propose something like this to resolve this problem :
```
// in src/TemplateCore.php
  public function __invoke() : string
  {
      $view = $this->getView();
      $data = (array) $this->getData();
      $this->content = ($view === null) ? '' : $this->render($view, $data);
      $layout = $this->getLayout();

      if ($layout === null) {
          return $this->content;
      }

      return $this->render($layout, $data);
  }
```

Alternative can be to merge `$__VARS__` with `$this->getData()` in `Template#render()` method.

I can make a PR if you want !

**Comment by pmjones** [comment]
>  `{{= $this->name}}` work but not `{{= $name}}` in template (Undefined variable $name)

That is the intended behavior; cf. https://qiqphp.com/1.x/data.html at the very bottom: "You can then use the data elements as if they are properties of $this inside the template."

The idea is to keep a separation between values that have been set "from outside" the template, and values that are defined "from inside" the template. So in `foreach ($this->values as $key => $value)`, `$this->value` was assigned to the template, but `$key` and `$value` are internal to the template.

Does that make sense?

**Comment by yoh** [comment]
Hello, thank for the reply !
I understand now my misunderstanding and it make sense... but i feel sad to need to repeat `$this->` everywhere (I'm a lazy guy). I'm a twig user and write `{{ $var }}` is a twig reflex :)

**Comment by pmjones** [comment]
> i feel sad to need to repeat $this-> everywhere

Yes, I understand. :-( Perhaps the 2.x version will go with just $var instead of $this->var, but I don't know when that will be (if at all).
