### ISSUE TITLE
Is there a way you can turn off the compiler

### ISSUE THREAD

**Issue by harikt** [qiqphp/qiq#8]
Basically the `{{` is used by some other front-end systems like vuejs.

I know we can escape the `{{`, but in case I don't need the sytax itself.

Do you think it is a good idea ? I have looked into the code, but seems the current compiler is hard coded inside the TemplateLocator .

**Comment by pmjones** [comment]
I could have sworn I had a `PhpCompiler` in there for just this occasion, but it looks like I do not (or at least, I took it out).

I will add back the PhpCompiler and roll a new release.

Meanwhile, if you look [here](https://github.com/qiqphp/qiq/blob/1.x/tests/TemplateLocatorTest.php#L12-L15) you will see how to set up the TemplateLocator with a compiler of your own. The [FakeCompiler](https://github.com/qiqphp/qiq/blob/1.x/tests/Compiler/FakeCompiler.php) is a PHP-only compiler. Try something like that, and let me know how it goes for you.

Sorry for the trouble!

**Comment by harikt** [comment]
Instead of cachepath, if you have passed the compiler https://github.com/qiqphp/qiq/blob/eead06305ba3fcc141c5d925fad2cc42b1b9eb15/src/Template.php#L17 then it would have been easy. But yes, I get how we can overcome it.

No sorry, no troubles here.

Thank you.

**Comment by pmjones** [comment]
I'm looking at it now, and it'll be easy enough to add a $compiler param *after* $cachePath, in which case $cachePath will be ignored, but whatever -- you'll be able to set the $compiler directly that way.

**Comment by harikt** [comment]
Another thought, may be not so useful. But just throwing here.

Turning on and off for each template
